name: Build

on:
  push:
    branches: [ nextgen ]
  pull_request:
    branches: [ nextgen ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/nextgen'
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setting up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Grant permissions to src-theme
        run: sudo chmod -R 777 src-theme

      - name: Setup and build
        uses: gradle/gradle-build-action@v3
        env:
          CI: true
        with:
          arguments: genSources build -x test -x detekt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
